# Generated by Django 6.0.1 on 2026-03-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cart_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wishlist_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
