# Generated by Django 6.0.1 on 2026-04-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_seller_userprofile_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_seller_pending',
            field=models.BooleanField(default=False),
        ),
    ]
