# Generated by Django 6.0.1 on 2026-04-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
