# Generated by Django 6.0.1 on 2026-04-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_orderitem_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tracking_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
